name: "test AWS Access"

# The workflow will trigger on any commit to the main branch
on:
  push:
    branches:
      - main

# Required to get the ID Token that will be used for OIDC
permissions:
  id-token: write
  contents: read # needed for private repos to checkout

jobs:
  aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-1
          role-to-assume: arn:aws:iam::441564410720:role/sts-lab-2-target
          role-session-name: OIDCSession

      - run: aws secretsmanager list-secrets
        shell: bash
